
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - backend

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USERNAME=root # không thực sự cần, MySQL chỉ cần MYSQL_ROOT_PASSWORD
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - backend


  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - backend
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8888:8888"
    command: [ "./wait-for.sh", "java", "-jar", "api-gateway.jar" ]
    environment:
      - IDENTITY_SERVICE_URL=http://identity-service:8080
      - PROFILE_SERVICE_URL=http://profile-service:8081
      - NOTIFICATION_SERVICE_URL=http://notification-service:8082
      - CHAT_SERVICE_URL=http://chat-service:8083
      - POST_SERVICE_URL=http://post-service:8084
      - STORY_SERVICE_URL=http://story-service:8086
      - JWT_SIGNER_KEY=15dbefda1f522778324fdbb8810d843bc5716214e793da2040db05b9fefc5e84
    networks:
      - backend

  identity-service:
    build: ./IdentityService
    container_name: identity-service
    ports:
      - "8080:8080"
    environment:
      - IDENTITY_SERVICE_URL=http://identity-service:8080
      - PROFILE_SERVICE_URL=http://profile-service:8081
      - NOTIFICATION_SERVICE_URL=http://notification-service:8082
      - CHAT_SERVICE_URL=http://chat-service:8083
      - POST_SERVICE_URL=http://post-service:8084
      - STORY_SERVICE_URL=http://story-service:8086
      - JWT_SIGNER_KEY=15dbefda1f522778324fdbb8810d843bc5716214e793da2040db05b9fefc5e84
    depends_on:
      - mysql
    command: [ "./wait-for.sh", "mysql", "3306", "java", "-jar", "IdentityService.jar" ]
    volumes:
      - ./wait-for.sh:/wait-for.sh
    networks:
      - backend


  chat-service:
    build: ./chat-service
    ports:
      - "8083:8083"
    depends_on:
      - mongo
    container_name: chat-service
    command: [ "./wait-for.sh", "mongodb", "27017", "java", "-jar", "chat-service.jar" ]
    environment:
      - IDENTITY_SERVICE_URL=http://identity-service:8080
      - PROFILE_SERVICE_URL=http://profile-service:8081
      - NOTIFICATION_SERVICE_URL=http://notification-service:8082
      - CHAT_SERVICE_URL=http://chat-service:8083
      - POST_SERVICE_URL=http://post-service:8084
      - STORY_SERVICE_URL=http://story-service:8086
      - JWT_SIGNER_KEY=15dbefda1f522778324fdbb8810d843bc5716214e793da2040db05b9fefc5e84
    volumes:
      - ./wait-for.sh:/wait-for.sh
    networks:
      - backend


  notification-service:
    build: ./notification-service
    container_name: notification_service
    ports:
      - "8082:8082"
    depends_on:
      - mongo
      - zookeeper
      - kafka
      - redis
    command: [ "./wait-for.sh", "mongodb", "27017",
               "zookeeper","2181",
               "kafka","9092",
               "redis","6379",
               "java", "-jar", "notification-service.jar" ]
    environment:
      - IDENTITY_SERVICE_URL=http://identity-service:8080
      - PROFILE_SERVICE_URL=http://profile-service:8081
      - NOTIFICATION_SERVICE_URL=http://notification-service:8082
      - CHAT_SERVICE_URL=http://chat-service:8083
      - POST_SERVICE_URL=http://post-service:8084
      - STORY_SERVICE_URL=http://story-service:8086
      - JWT_SIGNER_KEY=15dbefda1f522778324fdbb8810d843bc5716214e793da2040db05b9fefc5e84
    volumes:
      - ./wait-for.sh:/wait-for.sh
    networks:
      - backend



  post-service:
    build: ./post-service
    container_name: post-service
    ports:
      - "8084:8084"
    depends_on:
      - mongo
    command: [ "./wait-for.sh", "mongodb", "27017",
               "java", "-jar", "post-service.jar" ]
    environment:
      - IDENTITY_SERVICE_URL=http://identity-service:8080
      - PROFILE_SERVICE_URL=http://profile-service:8081
      - NOTIFICATION_SERVICE_URL=http://notification-service:8082
      - CHAT_SERVICE_URL=http://chat-service:8083
      - POST_SERVICE_URL=http://post-service:8084
      - STORY_SERVICE_URL=http://story-service:8086
      - JWT_SIGNER_KEY=15dbefda1f522778324fdbb8810d843bc5716214e793da2040db05b9fefc5e84
    volumes:
      - ./wait-for.sh:/wait-for.sh
    networks:
      - backend
  story-service:
    build: ./story-service
    container_name: story-service
    ports:
      - "8086:8086"
    depends_on:
      - mongo

    command: [ "./wait-for.sh", "mongodb", "27017",
               "java", "-jar", "story-service.jar" ]
    environment:
      - IDENTITY_SERVICE_URL=http://identity-service:8080
      - PROFILE_SERVICE_URL=http://profile-service:8081
      - NOTIFICATION_SERVICE_URL=http://notification-service:8082
      - CHAT_SERVICE_URL=http://chat-service:8083
      - POST_SERVICE_URL=http://post-service:8084
      - STORY_SERVICE_URL=http://story-service:8086
      - JWT_SIGNER_KEY=15dbefda1f522778324fdbb8810d843bc5716214e793da2040db05b9fefc5e84
    volumes:
      - ./wait-for.sh:/wait-for.sh
    networks:
      - backend
  profile-service:
    build: ./profile-service
    container_name: profile-service
    ports:
      - "8081:8081"
    depends_on:
      - neo4j
    command: [ "./wait-for.sh", "neo4j", "7474",
               "java", "-jar", "profile-service.jar" ]
    environment:
      - IDENTITY_SERVICE_URL=http://identity-service:8080
      - PROFILE_SERVICE_URL=http://profile-service:8081
      - NOTIFICATION_SERVICE_URL=http://notification-service:8082
      - CHAT_SERVICE_URL=http://chat-service:8083
      - POST_SERVICE_URL=http://post-service:8084
      - STORY_SERVICE_URL=http://story-service:8086
      - JWT_SIGNER_KEY=15dbefda1f522778324fdbb8810d843bc5716214e793da2040db05b9fefc5e84

    volumes:
      - neo4j_data:/data
      - ./wait-for.sh:/wait-for.sh
    networks:
      - backend
volumes:
  neo4j_data:
  mysql_data:
  mongo_data:

networks:
  backend:
    driver: bridge
