server:
  port: 8888

app:
  api-prefix: /api

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: https://identityservice-tspe.onrender.com/
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1

        - id: profile_service
          uri: https://profile-service-t9f6.onrender.com/
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=1

        - id: notification_service
          uri: http://notification-service:8082
          predicates:
            - Path=${app.api-prefix}/notification/**

          filters:
            - StripPrefix=1
            - RewritePath=/api/notification(?<segment>/?.*), /ws${segment}

        - id: chat_service
          uri: ws://chat-service:8083
          predicates:
            - Path=${app.api-prefix}/chat/ws/**
          filters:
            - RewritePath=/api/chat/(?<segment>/?.*), /chat/ws${segment}
        - id: post_service
          uri: http://post-service:8084
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=1


        - id: story_service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/stories/**
          filters:
            - StripPrefix=1
      httpclient:
        websocket:
          max-frame-payload-length: 65536