  server:
    port: 8084
    servlet:
      context-path: /post
  spring:
    application:
      name: post-service
    data:
      mongodb:
        uri: mongodb://root:root@host.docker.internal:27017/post-service?authSource=admin

  app:
    service:
      profile:
        url: "http://profile-service:8081/profile"
      notification:
        url: "http://notification-service:8082/notification"
      identity:
        url: "http://identity-service:8080/identity"