server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  neo4j:
    uri: bolt://host.docker.internal:7687
    authentication:
      username: "neo4j"
      password: "12345678"

app:
  services:
    identity: "http://identity-service:8080/identity"
    notification: "http://notification-service:8082/notification"