server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  neo4j:
    uri: "neo4j+s://40f14266.databases.neo4j.io"
    authentication:
      username: "neo4j"
      password: "ZVvmn4UtypyEh1aLxegraIKdM0y3QmOcia1kq3aOgUY"

app:
  services:
    identity: "https://identityservice-tspe.onrender.com/identity"
    notification: "http://notification-service:8082/notification"