server:
  port: 8086
  servlet:
    context-path: /stories
spring:
  application:
    name: story-service
  data:
    mongodb:
      uri: mongodb://root:root@host.docker.internal:27017/story-service?authSource=admin

app:
  service:
    profile:
      url: "http://localhost:8081/profile"
    notification:
      url: "http://localhost:8082/notification"
    identity:
      url: "http://localhost:8080/identity"