server:
  port: 8083
  servlet:
    context-path: /chat
spring:
  data:
    mongodb:
      uri: mongodb://root:root@host.docker.internal:27017/chat-service?authSource=admin
  websocket:
    # Enable WebSocket support
    enabled: true
app:
  service:
    profile:
      url: "http://profile-service:8081/profile"